[WIP]Exchange of node version at handshake.
AElfProject/AElf pull request #3332
Opened 2022-10-24 03:02 UTC by ssun0121

closes #3331

2022-11-23 08:57 UTC, jason-hoopox approved these changes

2022-11-24 07:53 UTC, LiWang-555 requested changes

2022-11-24 07:53 UTC, LiWang-555 commented on test/AElf.OS.Network.Grpc.Tests/Helpers/GrpcTestPeerHelper.cs
> +            {
It is highly recommended to write only one attribute assignment per line. Of course, it is acceptable to follow the original code pattern that placed all of assignments in a line, but it is not acceptable to place 3 in one line, and another in another line at the same time.

2022-11-26 05:26 UTC, LiWang-555 approved these changes
approve

2022-11-26 05:26 UTC, merged